image: python:3.9.6

stages:
  - test
  - push_to_github

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest tests

push_to_github:
  stage: push_to_github
  script:
    - |
      TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
      COMMIT_MESSAGE="CI: Passed all tests - $TIMESTAMP"
      git config --global user.email kahaan@gmail.com
      git config --global user.name KahaanGandhi
      git remote add github_repo https://github.com/KahaanGandhi/multi-armed-bandits.git
      git add .
      git commit -m "$COMMIT_MESSAGE"
      git push github_repo HEAD:master
  only:
    - master  # Only push to GitHub when changes are on the master branch
  dependencies:
    - test